import { map, catchError, EMPTY, concatMap, from } from 'rxjs';
import { executeCommandNewProcessToLinesObs } from '../execute-command/execute-command';
import { CommitCompact, CommitsByMonths } from './commit.model';

// fetchCommit is a function that fetched all the commits from a git repo and returns the sha of each commit and its date

// #copilot comment - the following comment has been added by copilot

// It uses the git log command to fetch the commits
// It returns an observable of an array of strings
// Each string is a commit sha and date separated by a comma
// The observable is an error if the command fails
export function fetchCommits(repoPath: string) {
    if (!repoPath) throw new Error(`Path is mandatory`);

    const command = `cd ${repoPath} && git log --pretty=format:"%H,%ad,%an"`;

    return executeCommandNewProcessToLinesObs(
        `Fetch commits`, 'git', ['log', '--pretty=format:%H,%ad,%an'],
        { cwd: repoPath }
    ).pipe(
        map((commits: string) => commits.split('\n')),
        concatMap((commits: string[]) => {
            return from(commits)
        }),
        map((commit: string) => {
            return newCommitCompact(commit)
        }),
        catchError((err: Error) => {
            console.error(`Error: "fetchCommits" while executing command "${command}" - error ${err.stack}`)
            return EMPTY
        })
    );
}

// newCommitCompact returns a new CommitCompact object with the given sha and date
export function newCommitCompact(data: string) {
    const shaDateAuthor = data.split(',')
    const commit: CommitCompact = {
        sha: shaDateAuthor[0],
        date: new Date(shaDateAuthor[1]),
        author: shaDateAuthor[2]
    }
    return commit
}

// commitsByMonth returns an array of CommitCompact objects grouped by month
// #copilot - the entire method has been generated by copilot, the only thing I changes was the key where copilot put
// month first and year second, I changed it to year first and month second
// I also changed the format of the month to be 2 digits
export function commitsByMonth(commits: CommitCompact[]) {
    const commitsByMonth = commits.reduce((acc, commit) => {
        const month = ("0" + (commit.date.getMonth() + 1)).slice(-2)
        const year = commit.date.getFullYear()
        const key = `${year}-${month}`
        if (!acc[key]) {
            acc[key] = {
                commits: [],
                authors: new Set<string>()
            }
        }
        acc[key].commits.push(commit)
        acc[key].authors.add(commit.author)
        return acc
    }, {} as CommitsByMonths)
    return commitsByMonth
}