import { map, catchError, EMPTY, concatMap, from, filter } from 'rxjs';
import { executeCommandNewProcessToLinesObs } from '../execute-command/execute-command';
import { CommitCompact, CommitPair, CommitsByMonths, newCommitPair, yearMonthFromDate } from './commit.model';

// fetchCommit is a function that fetched all the commits from a git repo and returns the sha of each commit and its date

// #copilot comment - the following comment has been added by copilot

// It uses the git log command to fetch the commits
// It returns an observable of an array of strings
// Each string is a commit sha and date separated by a comma
// The observable is an error if the command fails
export function fetchCommits(repoPath: string, fromDate = new Date(0), toDate = new Date(Date.now())) {
    if (!repoPath) throw new Error(`Path is mandatory`);

    const command = `cd ${repoPath} && git log --pretty=format:"%H,%ad,%an" --no-merges`;

    return executeCommandNewProcessToLinesObs(
        `Fetch commits`, 'git', ['log', '--pretty=format:%H,%ad,%an', '--no-merges'],
        { cwd: repoPath }
    ).pipe(
        map((commits: string) => commits.split('\n')),
        concatMap((commits: string[]) => {
            return from(commits)
        }),
        map((commit: string) => {
            return newCommitCompact(commit)
        }),
        filter((commit: CommitCompact) => {
            return commit.date >= fromDate && commit.date <= toDate
        }),
        catchError((err: Error) => {
            console.error(`Error: "fetchCommits" while executing command "${command}" - error ${err.stack}`)
            return EMPTY
        })
    );
}

// newCommitCompact returns a new CommitCompact object with the given sha and date
export function newCommitCompact(data: string) {
    const shaDateAuthor = data.split(',')
    const commit: CommitCompact = {
        sha: shaDateAuthor[0],
        date: new Date(shaDateAuthor[1]),
        author: shaDateAuthor[2]
    }
    return commit
}

// buildCommitPairArray is a function that receives an array of CommitCompact objects and returns an array of CommitPair objects
// where each CommitPair object contains two CommitCompact objects and the yearMonth of the second commit
export function buildCommitPairArray(commits: CommitCompact[], repoPath: string) {
    const commitPairs: CommitPair[] = []
    for (let i = 0; i < commits.length - 1; i++) {
        const commitPair = newCommitPair(repoPath, commits[i], commits[i + 1])
        commitPairs.push(commitPair)
    }
    return commitPairs
}

// commitsByMonth returns an instance of CommitsByMonths, where CommitCompact objects are grouped by month
// #copilot - the entire method has been generated by copilot, the only thing I changes was the key where copilot put
// month first and year second, I changed it to year first and month second
// I also changed the format of the month to be 2 digits
export function newCommitsByMonth(commits: CommitCompact[]) {
    const commitsByMonth = commits.reduce((acc, commit) => {
        const key = yearMonthFromDate(commit.date)
        if (!acc[key]) {
            acc[key] = {
                commits: [],
                authors: new Set<string>()
            }
        }
        acc[key].commits.push(commit)
        acc[key].authors.add(commit.author)
        return acc
    }, {} as CommitsByMonths)
    return commitsByMonth
}
