import { CommitCompact } from "./commit.model";

// CommitPair is a type that represents a tuple of 2 commits or null
// #copilot - the entire type has been generated by copilot after I have written the comment above
export type CommitPair = [CommitCompact, CommitCompact] | null;