// ClocLanguageStats is an interce that represents the statistics about a language
// produced by the cloc tool
// #copilot - the following interface was generated by copilot
export interface ClocLanguageStats {
    language: string;
    files: number;
    blank: number;
    comment: number;
    code: number;
}